

CREATE TABLE userProfile (
  id SERIAL PRIMARY KEY,
  firstName VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  birthday VARCHAR(100) NOT NULL,
  cam BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

INSERT INTO userProfile VALUES ('Danni', 'd123@dmail.com', 'April 2', FALSE);
